// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110181006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Float")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaintSeed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TradableAfter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TradeProtected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkinId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPrice = 4500m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Sport+Gloves+Pandora",
                            Name = "Sport Gloves | Pandora's Box",
                            Rarity = "Extraordinary",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = 2,
                            DefaultPrice = 680m,
                            ImageUrl = "https://community.fastly.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Tk5UvzWCL2kpn2-DFk_OKherB0H_qSCXKR09F-teB_Vmfjwkh_smuAzdasdniWaVNzAsYmQuYJ5hTsk4KxP-PhtAGI2opFzin_kGoXufyYXYCg/330x192?allow_animated=1",
                            Name = "Sport Gloves | Nocts",
                            Rarity = "Extraordinary",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = 3,
                            DefaultPrice = 700m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Moto+Gloves+Spearmint",
                            Name = "Moto Gloves | Spearmint",
                            Rarity = "Extraordinary",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = 4,
                            DefaultPrice = 290m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Specialist+Gloves+Foundation",
                            Name = "Specialist Gloves | Foundation",
                            Rarity = "Extraordinary",
                            Type = "Gloves"
                        },
                        new
                        {
                            Id = 5,
                            DefaultPrice = 3500m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Butterfly+Doppler",
                            Name = "Butterfly Knife | Doppler (Phase 4)",
                            Rarity = "Extraordinary",
                            Type = "Knife"
                        },
                        new
                        {
                            Id = 6,
                            DefaultPrice = 1500m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Karambit+Tiger+Tooth",
                            Name = "Karambit | Tiger Tooth",
                            Rarity = "Extraordinary",
                            Type = "Knife"
                        },
                        new
                        {
                            Id = 7,
                            DefaultPrice = 800m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Butterfly+Black+Laminate",
                            Name = "Butterfly Knife | Black Laminate",
                            Rarity = "Extraordinary",
                            Type = "Knife"
                        },
                        new
                        {
                            Id = 8,
                            DefaultPrice = 250m,
                            ImageUrl = "https://via.placeholder.com/300x200/EAB308/FFFFFF?text=Skeleton+Urban+Masked",
                            Name = "Skeleton Knife | Urban Masked",
                            Rarity = "Extraordinary",
                            Type = "Knife"
                        },
                        new
                        {
                            Id = 9,
                            DefaultPrice = 80m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Vypa+Sista",
                            Name = "Vypa Sista of the Revolution | Guerrilla Warfare",
                            Rarity = "Restricted",
                            Type = "Agent"
                        },
                        new
                        {
                            Id = 10,
                            DefaultPrice = 70m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Number+K",
                            Name = "Number K | The Professionals",
                            Rarity = "Restricted",
                            Type = "Agent"
                        },
                        new
                        {
                            Id = 11,
                            DefaultPrice = 1049m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AK-47+Fire+Serpent",
                            Name = "AK-47 | Fire Serpent",
                            Rarity = "Covert",
                            Type = "Rifle"
                        },
                        new
                        {
                            Id = 12,
                            DefaultPrice = 100m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=M4A4+X-Ray",
                            Name = "M4A4 | X-Ray",
                            Rarity = "Covert",
                            Type = "Rifle"
                        },
                        new
                        {
                            Id = 13,
                            DefaultPrice = 33m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AK-47+Head+Shot",
                            Name = "AK-47 | Head Shot",
                            Rarity = "Covert",
                            Type = "Rifle"
                        },
                        new
                        {
                            Id = 14,
                            DefaultPrice = 33m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=USP-S+Printstream",
                            Name = "USP-S | Printstream",
                            Rarity = "Covert",
                            Type = "Pistol"
                        },
                        new
                        {
                            Id = 15,
                            DefaultPrice = 30m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=Desert+Eagle+Printstream",
                            Name = "Desert Eagle | Printstream",
                            Rarity = "Covert",
                            Type = "Pistol"
                        },
                        new
                        {
                            Id = 16,
                            DefaultPrice = 16m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=Glock+Gold+Toof",
                            Name = "Glock-18 | Gold Toof",
                            Rarity = "Covert",
                            Type = "Pistol"
                        },
                        new
                        {
                            Id = 17,
                            DefaultPrice = 115m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=MAC-10+Neon+Rider",
                            Name = "MAC-10 | Neon Rider",
                            Rarity = "Covert",
                            Type = "SMG"
                        },
                        new
                        {
                            Id = 18,
                            DefaultPrice = 3m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=MP7+Fade",
                            Name = "MP7 | Fade 99%",
                            Rarity = "Restricted",
                            Type = "SMG"
                        },
                        new
                        {
                            Id = 19,
                            DefaultPrice = 53m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AWP+Printstream",
                            Name = "AWP | Printstream",
                            Rarity = "Covert",
                            Type = "Sniper Rifle"
                        });
                });

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.HasOne("backend.Models.Skin", "Skin")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
