// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Float")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaintSeed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TradableAfter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TradeProtected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkinId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Weapon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Collection = "Bravo",
                            DefaultPrice = 1049m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AK-47+Fire+Serpent",
                            Name = "AK-47 | Fire Serpent",
                            Rarity = "Covert",
                            Type = "Rifle",
                            Weapon = "AK-47"
                        },
                        new
                        {
                            Id = 2,
                            Collection = "Cobblestone",
                            DefaultPrice = 5000m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AWP+Dragon+Lore",
                            Name = "AWP | Dragon Lore",
                            Rarity = "Covert",
                            Type = "Sniper Rifle",
                            Weapon = "AWP"
                        },
                        new
                        {
                            Id = 3,
                            Collection = "Huntsman",
                            DefaultPrice = 3000m,
                            ImageUrl = "https://via.placeholder.com/300x200/F97316/FFFFFF?text=M4A4+Howl",
                            Name = "M4A4 | Howl",
                            Rarity = "Contraband",
                            Type = "Rifle",
                            Weapon = "M4A4"
                        },
                        new
                        {
                            Id = 4,
                            Collection = "Dust",
                            DefaultPrice = 250m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Deagle+Blaze",
                            Name = "Desert Eagle | Blaze",
                            Rarity = "Restricted",
                            Type = "Pistol",
                            Weapon = "Desert Eagle"
                        },
                        new
                        {
                            Id = 5,
                            Collection = "Assault",
                            DefaultPrice = 150m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Glock+Fade",
                            Name = "Glock-18 | Fade",
                            Rarity = "Restricted",
                            Type = "Pistol",
                            Weapon = "Glock-18"
                        });
                });

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.HasOne("backend.Models.Skin", "Skin")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
