// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoverageTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SelectedTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SkinAltImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("SkinId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinRarity")
                        .HasColumnType("text");

                    b.Property<string>("SkinType")
                        .HasColumnType("text");

                    b.Property<string>("SkinWeapon")
                        .HasColumnType("text");

                    b.Property<decimal>("SurplusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("backend.Models.GoalSelectedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceInventoryItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("TradeProtected")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Weapon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalSelectedItems");
                });

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Float")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PaintSeed")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkinId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TradableAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TradeProtected")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("SkinId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.LoadoutFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoadoutFavorites");
                });

            modelBuilder.Entity("backend.Models.LoadoutFavoriteEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoadoutFavoriteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SkinId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Weapon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("LoadoutFavoriteId");

                    b.HasIndex("SkinId");

                    b.ToTable("LoadoutFavoriteEntries");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Collection")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PaintIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Weapon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Collection = "Bravo",
                            DefaultPrice = 1049m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AK-47+Fire+Serpent",
                            Name = "AK-47 | Fire Serpent",
                            Rarity = "Covert",
                            Type = "Rifle",
                            Weapon = "AK-47"
                        },
                        new
                        {
                            Id = 2,
                            Collection = "Cobblestone",
                            DefaultPrice = 5000m,
                            ImageUrl = "https://via.placeholder.com/300x200/DC2626/FFFFFF?text=AWP+Dragon+Lore",
                            Name = "AWP | Dragon Lore",
                            Rarity = "Covert",
                            Type = "Sniper Rifle",
                            Weapon = "AWP"
                        },
                        new
                        {
                            Id = 3,
                            Collection = "Huntsman",
                            DefaultPrice = 3000m,
                            ImageUrl = "https://via.placeholder.com/300x200/F97316/FFFFFF?text=M4A4+Howl",
                            Name = "M4A4 | Howl",
                            Rarity = "Contraband",
                            Type = "Rifle",
                            Weapon = "M4A4"
                        },
                        new
                        {
                            Id = 4,
                            Collection = "Dust",
                            DefaultPrice = 250m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Deagle+Blaze",
                            Name = "Desert Eagle | Blaze",
                            Rarity = "Restricted",
                            Type = "Pistol",
                            Weapon = "Desert Eagle"
                        },
                        new
                        {
                            Id = 5,
                            Collection = "Assault",
                            DefaultPrice = 150m,
                            ImageUrl = "https://via.placeholder.com/300x200/A855F7/FFFFFF?text=Glock+Fade",
                            Name = "Glock-18 | Fade",
                            Rarity = "Restricted",
                            Type = "Pistol",
                            Weapon = "Glock-18"
                        });
                });

            modelBuilder.Entity("backend.Models.Sticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarFullUrl")
                        .HasColumnType("text");

                    b.Property<string>("AvatarMediumUrl")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Goal", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.GoalSelectedItem", b =>
                {
                    b.HasOne("backend.Models.Goal", "Goal")
                        .WithMany("SelectedItems")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.HasOne("backend.Models.Skin", "Skin")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.LoadoutFavorite", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("LoadoutFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.LoadoutFavoriteEntry", b =>
                {
                    b.HasOne("backend.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.LoadoutFavorite", "Loadout")
                        .WithMany("Entries")
                        .HasForeignKey("LoadoutFavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Skin", "Skin")
                        .WithMany()
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InventoryItem");

                    b.Navigation("Loadout");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("backend.Models.Sticker", b =>
                {
                    b.HasOne("backend.Models.InventoryItem", "InventoryItem")
                        .WithMany("Stickers")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("backend.Models.Goal", b =>
                {
                    b.Navigation("SelectedItems");
                });

            modelBuilder.Entity("backend.Models.InventoryItem", b =>
                {
                    b.Navigation("Stickers");
                });

            modelBuilder.Entity("backend.Models.LoadoutFavorite", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("InventoryItems");

                    b.Navigation("LoadoutFavorites");
                });
#pragma warning restore 612, 618
        }
    }
}
